"""Document writers.

``write_document(path, content, *, kind=None)`` creates a real file on disk,
choosing the format from the path suffix (or ``kind``, which overrides it):

* ``.docx`` -> python-docx: ``content`` (str) split into paragraphs by newline.
* ``.xlsx`` -> openpyxl: a ``list[list]`` writes rows; a str writes one cell per
  line in column A.
* ``.pptx`` -> python-pptx: a title slide plus a bullet slide built from the
  content lines.
* ``.pdf``  -> fpdf2: ``multi_cell`` the text (Latin-1 sanitised so fpdf2 never
  crashes on non-Latin-1 characters).
* ``.csv``  -> stdlib csv from a ``list[list]`` or from text lines.
* ``.txt/.md`` and anything else -> UTF-8 text.

Parent directories are created as needed; the written :class:`Path` is returned.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

#: Suffixes with a dedicated writer (everything else falls back to UTF-8 text).
SUPPORTED_WRITE: set[str] = {
    ".docx",
    ".xlsx",
    ".pptx",
    ".pdf",
    ".csv",
    ".txt",
    ".md",
    ".json",
    ".html",
    ".log",
    ".yaml",
    ".yml",
}


def write_document(
    path: str | Path, content: Any, *, kind: str | None = None
) -> Path:
    """Write ``content`` to ``path`` as a real document. Returns the Path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    suffix = ("." + kind.lstrip(".")).lower() if kind else p.suffix.lower()

    if suffix == ".docx":
        _write_docx(p, content)
    elif suffix == ".xlsx":
        _write_xlsx(p, content)
    elif suffix == ".pptx":
        _write_pptx(p, content)
    elif suffix == ".pdf":
        _write_pdf(p, content)
    elif suffix == ".csv":
        _write_csv(p, content)
    else:
        _write_text(p, content)
    return p


# --- helpers ------------------------------------------------------------------


def _as_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, (list, tuple)):
        return "\n".join(
            "\t".join(str(c) for c in row)
            if isinstance(row, (list, tuple))
            else str(row)
            for row in content
        )
    return str(content)


def _as_lines(content: Any) -> list[str]:
    return _as_text(content).split("\n")


# --- format writers -----------------------------------------------------------


def _write_docx(p: Path, content: Any) -> None:
    import docx

    doc = docx.Document()
    for line in _as_lines(content):
        doc.add_paragraph(line)
    doc.save(str(p))


def _write_xlsx(p: Path, content: Any) -> None:
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    if isinstance(content, (list, tuple)):
        for row in content:
            if isinstance(row, (list, tuple)):
                ws.append([("" if c is None else c) for c in row])
            else:
                ws.append([row])
    else:
        for line in _as_lines(content):
            ws.append([line])
    wb.save(str(p))


def _write_pptx(p: Path, content: Any) -> None:
    import pptx

    lines = [ln for ln in _as_lines(content)]
    title = lines[0] if lines and lines[0].strip() else "Document"

    prs = pptx.Presentation()

    # Title slide.
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by Iron Jarvis"

    # Bullet slide carrying every content line.
    bullet_slide = prs.slides.add_slide(prs.slide_layouts[1])
    bullet_slide.shapes.title.text = title
    body = bullet_slide.placeholders[1].text_frame
    first, *rest = lines or [""]
    body.text = first
    for line in rest:
        body.add_paragraph().text = line

    prs.save(str(p))


def _write_pdf(p: Path, content: Any) -> None:
    from fpdf import FPDF

    text = _as_text(content)
    # Core fonts are Latin-1 only; replace anything outside it so fpdf2 cannot crash.
    safe = text.encode("latin-1", "replace").decode("latin-1")
    if not safe.strip():
        safe = " "

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    pdf.multi_cell(0, 8, safe)
    pdf.output(str(p))


def _write_csv(p: Path, content: Any) -> None:
    with open(p, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if isinstance(content, (list, tuple)):
            for row in content:
                if isinstance(row, (list, tuple)):
                    writer.writerow(list(row))
                else:
                    writer.writerow([row])
        else:
            for line in _as_lines(content):
                writer.writerow([line])


def _write_text(p: Path, content: Any) -> None:
    p.write_text(_as_text(content), encoding="utf-8")
